spring.application.name=security-II-test

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/tp
spring.datasource.username=root
spring.datasource.password=123456
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

jwt.seceret=f0fea0e484326bf018d856cd4f0f16126f13dfdd33ea1faa1d9f76b192da6bc7
jwt.expiration=86400000